### ISSUE TITLE
Solutions cannot be opened in Visual Studio 2017

### ISSUE THREAD

**Issue by Foroughi** [zapezhman/FFWSC#2]
There are two sln files , neither can be opened in Visual studio. Im assumming you have forgotten to save your solution. Please refer to the attached images. 

![New Bitmap Image](https://user-images.githubusercontent.com/3727486/89615539-2586d780-d887-11ea-9a71-651e6c608b12.jpg)

![New Bitmap Image (2)](https://user-images.githubusercontent.com/3727486/89615541-261f6e00-d887-11ea-8d05-7e9fa4294b6e.jpg)

**Comment by begininvoke** [comment]
Hi, issue was fixed and  is compatible with visual studio 2019 now
<img width="345" alt="Screen Shot 2020-08-07 at 10 15 42 PM" src="https://user-images.githubusercontent.com/56797886/89673611-e47cda80-d8fb-11ea-8573-bcdd99674d68.png">
<img width="312" alt="Screen Shot 2020-08-07 at 10 15 51 PM" src="https://user-images.githubusercontent.com/56797886/89673621-e9da2500-d8fb-11ea-8f34-29ec19312eb7.png">
