### ISSUE TITLE
Brief Review

### ISSUE THREAD

**Issue by Foroughi** [zapezhman/FFWSC#3]
I just had a breif review on the codes. Im still being kept in dark about the idea of using **Reflection** to call **FFWC_Core.exe** and TBH im still tring to comprehend the concept behind that. This is while you simply can have a shared library and use it in both projects. But then again, I just had a brief review. maybe you have an idea behind that logic.

The other thing that actually pissed me off was that you have literally mixed up the presentation layer of your application with your logic.Obviously your code is suffering because of a missing design pattern. This is for sure totaly rejected and unrecommended. Mixing the layers is easy inevitable by seperating the codes with different goals and break them into distinguished standalone modules. 

In large or even medium scaled projects, mixing the application tiers with one another will cause serious unrecoverable damages which eventually will causes of failover. Having no rule for your application tiers or  precisely having no design pattern will cause this : 

![Untitled](https://user-images.githubusercontent.com/3727486/90032535-c0841500-dcbe-11ea-9dae-d7b128c59518.png)

So my suggestion is to follow a design pattern. maybe the combination of N-tier and MVVM will be good for WPF applications . 

Another idea of having a good , clean and fancy codes is to use a **Roslyn-based** analyzers. Out there , there are lots of analyzers that you can take the advantages of using them to have a better code or even in some cases, to avoid silly mistakes. 

anyway , well-done and finger crossed mate.

**Comment by begininvoke** [comment]
I will definitely make good changes in the new version based on your great comments. Thank you for your review and comment. Good luck
